camunda:
  client:
    mode: self-managed
    auth:
        method:none
    worker:
      defaults:
        max-jobs-active: 10
        # https://docs.camunda.io/docs/apis-tools/camunda-spring-boot-starter/configuration/#define-the-job-timeout
        timeout: PT2M
        stream-enabled: true

    grpc-address: http://127.0.0.1:26500
    execution-threads: 10
    prefer-rest-over-grpc: true

zeebe:
  operateUsername: demo
  operatePassword: demo
  operateUrl: http://localhost:8081

  worker:

    # the time to execute the job are homogeneous (5 s each) or not (5 to 15 s each)
    homegeneousWorker: false

    # set the value to the same as job active. then, we are sure this maximum thread are created
    semaphore: 10

    # size of the list = number of execution for the worker
    sizelist: 500

workerapplication:
  runTests: true
  # Specify the list of test to run automatically
  # List is Classical Worker,Thread Worker,Thread Token Worker,Asynchronous Worker
  # runListTests: Classical,Thread,ThreadToken,Asynchronous
  runListTests2: Classical,Thread,ThreadToken,Asynchronous

  runListTests: Classical

  # for a test, give the Stream mode: NOSTREAM, YES: STREAM, ALL: both (2 tests)
  # NOSTREAM, STREAM, ALL
  runModeStream: STREAM
  # for a test, give the Heterogeneous mode: HETEROGENEOUS, HOMOGENEOUS, ALL: both (2 tests)
  # HETEROGENEOUS, HOMOGENEOUS, ALL
  runModeHeterogeneous: HETEROGENEOUS

  monitor:
    logjobs: false
    # if true, then jobs are registered to track any double execution. This implie a synchronization in the code
    registerjobs: false


logging:
  level:
    root: INFO
#  file:
#    name: log/application-workerimpl.log

spring22:
  output:
    ansi:
      enabled: DETECT
